export const contentType = [
  { type: "관광지", id: "12", img: "/images/관광지.png",infoList: [
    {th: "문의 및 안내", td: "infocenter"},
    {th: "개장일", td: "opendate"},
    {th: "쉬는날", td: "restdate"},
    {th: "이용시간", td: "usetime"},
    {th: "주차시설", td: "parking"},
  ]},
  { type: "문화시설", id: "14", img: "/images/문화시설.png",infoList: [
    {th: "문의 및 안내", td: "infocenterculture"},
    {th: "쉬는날", td: "restdateculture"},
    {th: "이용시간", td: "usetimeculture"},
    {th: "이용요금", td: "usefee"},
    {th: "주차시설", td: "parkingculture"},
  ]},
  { type: "축제공연행사", id: "15", img:"/images/축제공연행사.png",infoList: [
    {th: "주최자 정보", td: "sponsor1"},
    {th: "주최자 연락처", td: "sponsor1tel"},
    {th: "관람가능연령", td: "agelimit"},
    {th: "행사장소", td: "eventplace"},
    {th: "행사시작일", td: "eventstartdate"},
    {th: "행사종료일", td: "eventenddate"},
    {th: "공연시간", td: "playtime"},
  ]},
  { type: "레포츠", id: "28", img:"/images/레포츠.png", infoList: [
    {th: "문의 및 안내", td: "infocenterleports"},
    {th: "쉬는날", td: "restdateleports"},
    {th: "이용시간", td: "usetimeleports"},
    {th: "주차시설", td: "parkingleports"},
  ]},
  { type: "숙박", id: "32", img:"/images/숙박.png",  infoList: [
    {th: "문의 및 안내", td: "infocenterlodging"},
    {th: "객실 수", td: "roomcount"},
    {th: "주차가능", td: "parkinglodging"},
    {th: "조리가능", td: "chkcooking"},
    {th: "체크인", td: "checkintime"},
    {th: "체크아웃", td: "checkouttime"},
    {th: "예약안내", td: "reservationlodging"},
    {th: "예약안내 홈페이지", td: "reservationurl"},
    {th: "환불규정", td: "refundregulation"},
  ]},
  { type: "쇼핑", id: "38", img:"/images/쇼핑.png", infoList: [
    {th: "문의 및 안내", td: "infocentershopping"},
    {th: "판매품목", td: "saleitem"},
    {th: "영업시간", td: "opentime"},
    {th: "쉬는날", td: "restdateshopping"},
    {th: "매장안내", td: "shopguide"},
    {th: "주차시설", td: "parkingshopping"},
  ]},
  { type: "음식점", id: "39", img: "/images/음식점.png", infoList: [
    {th: "문의 및 안내", td: "infocenterfood"},
    {th: "쉬는날", td: "restdatefood"},
    {th: "영업시간", td: "opentimefood"},
    {th: "대표메뉴", td: "firstmenu"},
    {th: "주차시설", td: "parkingfood"},
  ]},
];